require("prototypes.entity.resources")
require("prototypes.entity.entities")
require("prototypes.item.item")
require("prototypes.fluid.fluids")
require("prototypes.recipe.assembler-recipe")
require("prototypes.recipe.recipe")
require("prototypes.recipe.smeltingRecipe")
require("prototypes.categories.recipe-category")
require("prototypes.recipe.mixer-recipe")
require("prototypes.recipe.chemical-recipe")
require("prototypes.recipe.pulveriser-recipe")
require("prototypes.recipe.rotary-kiln-recipe")
require("prototypes.autoplace-controls")

require("prototypes.tile.noise-layers")
require("prototypes.entity.wall")